# Generated by Django 4.2.15 on 2024-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Введите дату",
                verbose_name="Дата создания записи",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Введите дату",
                verbose_name="Дата изменения записи",
            ),
        ),
    ]
