# Generated by Django 4.2.15 on 2024-09-30 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_alter_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price_pay"],
                "permissions": [("set_published", "Can publish posts")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
