# Generated by Django 4.2.15 on 2024-09-30 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price_pay"],
                "permissions": [
                    ("can_edit_category", "Can edit category"),
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_is_published", "Can edit is_published"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
